'use strict';
const assert = require('assert');
const make = require('./matchmaker');
const clients = {};
function client(id) { return clients[id] = {id, place:0, socket:{readyState:1}, events:[], send(type,data){this.events.push(data);}}; }
const a = client('a'), b = client('b'), c = client('c');
let result;
const mm = make(clients, (players,dictionary) => { result={players,dictionary}; });
mm.join(a); mm.join(a);
assert.equal(a.events.length,1);
mm.join(b);
assert.equal(a.events.at(-1).state,'vote');
mm.vote(c,'basic'); mm.vote(a,'invalid');
assert.equal(result,undefined);
mm.vote(a,'basic'); mm.vote(a,'complex');
assert.equal(result,undefined);
mm.vote(b,'basic');
assert.equal(result.dictionary,'basic');
assert.deepEqual(result.players,[a,b]);
result=undefined;
mm.join(a); mm.join(b); mm.vote(a,'standard'); mm.vote(b,'complex');
assert.ok(['standard','complex'].includes(result.dictionary));
mm.join(a); mm.join(b); mm.cancel(a);
assert.equal(b.events.at(-1).state,'cancelled');
result=undefined;
mm.join(a); mm.join(b); b.socket.readyState=3; mm.vote(a,'basic');
assert.equal(result,undefined);
assert.equal(a.events.at(-1).state,'cancelled');
mm.close();
console.log('PASS: duplicate queue, two-player pairing, vote validation, majority/tie, cancellation, disconnect');
