/* Private friend windows live outside game panels so room transitions do not close them. */
$(function(){
 var active=null,records={},oldest=null,hasMore=false,busy=false,historyBusy=false,seen={},friends=[],lastPoll=0,unreadByPeer={};
 var community=$('<section id="FriendsCommunity" class="friend-window" hidden><header class="friend-window-head"><img src="/img/custom/chat-brand-white.png" alt="끄투"><h2>친구/커뮤니티</h2><button class="friend-close" aria-label="친구 목록 닫기">×</button></header><div class="friend-list"></div><footer><button class="friend-add">친구 추가</button></footer></section>').appendTo('body');
 var dm=$('<section id="FriendConversation" class="friend-window" hidden><header class="friend-window-head"><img src="/img/custom/chat-brand-white.png" alt="끄투"><div><h2></h2><p>대화는 친구를 삭제하기 전까지 저장됩니다.</p></div><button class="friend-close" aria-label="친구 채팅 닫기">×</button></header><button class="friend-older" hidden>이전 대화 보기</button><div class="friend-messages" role="log" aria-live="polite"></div><p class="friend-error" role="status"></p><form><input maxlength="200" placeholder="채팅 입력" aria-label="친구에게 보낼 메시지"><button type="submit">전송</button></form></section>').appendTo('body');
 var alerts=$('<div id="FriendAlerts" aria-live="polite"></div>').appendTo('body');
 var launcher=$('<button id="FriendLauncher" type="button" title="친구 목록"><img src="/img/custom/friends-icon.svg" alt=""><span>친구</span><b class="friend-launcher-unread" hidden></b></button>').appendTo('body');
 var loginLauncher=$('<button id="GuestLoginLauncher" type="button">로그인</button>').hide().appendTo('body').on('click',function(){if(window.KkutuAccount)window.KkutuAccount.login();else location.href='/?account=login';});
 var levelRanking=$('<section id="LevelRankingPanel" hidden><header><h2>레벨 랭킹</h2><button type="button" aria-label="랭킹 닫기">×</button></header><p class="level-ranking-status">현재 레벨이 높은 순서로 불러오는 중입니다.</p><div class="level-ranking-list"></div></section>').appendTo('body');
 var levelRankingButton=$('<button id="LevelRankingBtn" class="for-lobby" type="button" aria-label="레벨 랭킹"><img src="/img/custom/ranking-icon.svg" alt=""><strong class="level-ranking-button-label">랭킹</strong></button>').hide().appendTo('.kkutu-menu');
 function api(path,data){return $.ajax({url:'/api/friend-chat/'+path,method:data?'POST':'GET',contentType:data?'application/json':undefined,data:data?JSON.stringify(data):undefined,headers:{'X-Requested-With':'XMLHttpRequest'}});}
 function error(e){return e.responseJSON&&e.responseJSON.error||'연결을 확인하고 다시 시도해 주세요.';}
 function display(panel){panel.appendTo('body').prop('hidden',false);keepOnScreen(panel);}
 function keepOnScreen(panel){if(panel.prop('hidden'))return;var r=panel[0].getBoundingClientRect();panel.css({left:Math.max(8,Math.min(r.left,innerWidth-r.width-8)),top:Math.max(8,Math.min(r.top,innerHeight-r.height-8))});}
 function movable(panel,key){var saved;try{saved=JSON.parse(localStorage.getItem(key));}catch(e){}panel.css(saved||{left:Math.max(8,(innerWidth-440)/2),top:Math.max(12,(innerHeight-500)/2)});
  panel.find('header').on('pointerdown',function(ev){if($(ev.target).closest('button').length)return;var e=ev.originalEvent||ev,r=panel[0].getBoundingClientRect(),x=e.clientX,y=e.clientY;e.preventDefault();this.setPointerCapture(e.pointerId);$(window).on('pointermove.friendDrag',function(ev){var m=ev.originalEvent||ev;panel.css({left:Math.max(8,Math.min(innerWidth-r.width-8,r.left+m.clientX-x)),top:Math.max(8,Math.min(innerHeight-r.height-8,r.top+m.clientY-y))});}).one('pointerup.friendDrag pointercancel.friendDrag',function(){$(window).off('.friendDrag');try{localStorage.setItem(key,JSON.stringify({left:parseFloat(panel.css('left')),top:parseFloat(panel.css('top'))}));}catch(e){}});});
  panel.find('.friend-close').on('click',function(){panel.prop('hidden',true);});
 }
 movable(community,'kkutu-friends-position');movable(dm,'kkutu-dm-position');$(window).on('resize',function(){keepOnScreen(community);keepOnScreen(dm);});
 function name(id){var f=friends.filter(function(f){return f.id===id;})[0];return f?f.name:($data.friends||{})[id]||'친구';}
 function renderFriends(){var list=community.find('.friend-list').empty();if(!friends.length)list.append($('<p>').text('등록된 친구가 없습니다. 프로필에서 친구를 추가해 주세요.'));friends.forEach(function(f){var row=$('<div class="friend-row">').appendTo(list);var identity=$('<div class="friend-identity">').appendTo(row);$('<strong>').text(f.name).appendTo(identity);var status=($data._friends||{})[f.id],online=!!($data.users||{})[f.id]||!!(status&&status.server!==false&&status.server!=null);$('<span class="friend-online">').toggleClass('is-online',online).text(online?'온라인':'오프라인').appendTo(identity);$('<button class="friend-open">').text('채팅').appendTo(row).on('click',function(){open(f.id);});$('<button class="friend-delete">').text('삭제').appendTo(row).on('click',function(){if(!confirm(f.name+'님을 친구에서 삭제할까요? 두 사람의 대화 기록도 삭제됩니다.'))return;send('friendRemove',{id:f.id},true);if(active===f.id){active=null;records={};dm.find('.friend-messages').empty();dm.prop('hidden',true);}alerts.children().filter(function(){return $(this).attr('data-peer')===f.id;}).remove();row.remove();setTimeout(poll,500);});});}
 window.openFriendCommunity=function(){if($data.guest)return fail(451);display(community);poll();};
 if($stage.menu.community)$stage.menu.community.empty().append($('<img>').attr({src:'/img/custom/friends-icon.svg',alt:''})).append($('<span>').text('친구')).attr('title','친구/커뮤니티').off('click').on('click',window.openFriendCommunity);launcher.on('click',window.openFriendCommunity);
 community.find('.friend-add').on('click',function(){$stage.dialog.commFriendAdd.trigger('click');});
 function markerKey(kind,id){return 'kkutu-friend-'+kind+':'+$data.id+':'+id;}
 function marker(kind,id){try{return localStorage.getItem(markerKey(kind,id))||'0';}catch(e){return '0';}}
 function newer(a,b){a=String(a);b=String(b);return a.length!==b.length?a.length>b.length:a>b;}
 function remember(kind,id,last){if(newer(last,marker(kind,id)))try{localStorage.setItem(markerKey(kind,id),String(last));}catch(e){}}
 function removeAlert(peer){alerts.children('[data-peer]').filter(function(){return $(this).attr('data-peer')===peer;}).remove();}
 function renderUnread(){var count=Object.keys(unreadByPeer).reduce(function(sum,id){return sum+(Number(unreadByPeer[id])||0);},0),badge=launcher.find('.friend-launcher-unread');badge.text(count>99?'99+':count).prop('hidden',count<1);}
 function markRead(peer,id){remember('read',peer,id);seen[peer]=id;unreadByPeer[peer]=0;renderUnread();removeAlert(peer);return api('read',{peer:peer,id:id}).fail(function(){dm.find('.friend-error').text('읽음 상태 저장을 다시 시도하고 있습니다.');});}
 function alertFriend(id,last){if(!newer(last,marker('read',id))||seen[id]===last)return;seen[id]=last;removeAlert(id);var card=$('<section class="friend-toast">').attr('data-peer',id).appendTo(alerts);$('<strong>').text(name(id)+'님에게 채팅이 왔어요').appendTo(card);$('<button class="friend-go">').text('채팅 하러 가기').appendTo(card).on('click',function(){markRead(id,last);open(id);});$('<button class="friend-dismiss">').text('닫기').appendTo(card).on('click',function(){markRead(id,last);});}
 function open(id){community.prop('hidden',true);if(active!==id){active=id;records={};oldest=null;hasMore=false;dm.find('.friend-messages').empty();}dm.find('h2').text(name(id)+' 채팅');dm.find('.friend-error').empty();display(dm);alerts.children().filter(function(){return $(this).attr('data-peer')===id;}).remove();load(false);dm.find('input').focus();}
 window.openFriendConversation=open;
 function paint(){var box=dm.find('.friend-messages'),node=box[0],atBottom=node.scrollHeight-node.scrollTop-node.clientHeight<50;var rows=Object.keys(records).sort(function(a,b){return Number(a)-Number(b);});box.empty();rows.forEach(function(id){var m=records[id],row=$('<div class="friend-message">').appendTo(box);var content=$('<div>').appendTo(row);$('<b>').text(m.sender===$data.id?'나':m.sender_name).appendTo(content);content.append(document.createTextNode(': '+m.body));$('<time>').text(new Date(Number(m.created_at)).toLocaleString('ko-KR',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'})).appendTo(row);$('<button>').text('신고').appendTo(row).on('click',function(){var button=$(this);if(!confirm('이 메시지를 운영자에게 신고할까요?'))return;api('report',{id:m.id}).done(function(){button.prop('disabled',true).text('신고됨');}).fail(function(e){dm.find('.friend-error').text(error(e));});});});if(atBottom)node.scrollTop=node.scrollHeight;}
 function load(older){if(!active||dm.prop('hidden')||historyBusy)return;var peer=active;historyBusy=true;var box=dm.find('.friend-messages')[0],height=box.scrollHeight,scroll=box.scrollTop;api('history?peer='+encodeURIComponent(peer)+(older&&oldest?'&before='+oldest:'')).done(function(data){if(active!==peer)return;data.messages.forEach(function(m){records[m.id]=m;});if(older||oldest===null){hasMore=data.hasMore;oldest=data.messages.length?data.messages[0].id:oldest;}paint();if(older)box.scrollTop=scroll+box.scrollHeight-height;dm.find('.friend-older').prop('hidden',!hasMore);if(!dm.prop('hidden')&&!document.hidden){var ids=data.messages.filter(function(m){return m.sender===peer;}).map(function(m){return m.id;});if(ids.length)markRead(peer,ids[ids.length-1]);}}).fail(function(e){if(active!==peer)return;dm.find('.friend-error').text(error(e));if(e.status===403){records={};dm.find('.friend-messages').empty();}}).always(function(){historyBusy=false;});}
 dm.find('.friend-older').on('click',function(){load(true);});
 dm.find('input').on('keydown keyup keypress',function(e){e.stopPropagation();if(e.type==='keydown'&&e.key==='Enter'&&(e.isComposing||(e.originalEvent&&e.originalEvent.isComposing)))e.preventDefault();});
 dm.find('form').on('submit',function(e){e.preventDefault();if(busy||!active)return;var input=dm.find('input'),value=input.val().trim(),peer=active;if(!value)return;busy=true;dm.find('[type=submit]').prop('disabled',true);api('send',{peer:peer,value:value}).done(function(data){if(active!==peer)return;records[data.message.id]=data.message;input.val('');paint();dm.find('.friend-messages').scrollTop(9999999);dm.find('.friend-error').empty();}).fail(function(e){dm.find('.friend-error').text(error(e));}).always(function(){busy=false;dm.find('[type=submit]').prop('disabled',false);});});
 function isGuest(){var marker=$('#IS_GUEST').text().trim();if(marker==='false')return false;if(marker==='true')return true;return !$data.id||$data.guest===true;}
 function poll(){var guest=isGuest();launcher.toggle(!guest);loginLauncher.toggle(guest);if(guest){unreadByPeer={};renderUnread();return;}if(Date.now()-lastPoll<1000)return;lastPoll=Date.now();api('inbox').done(function(data){friends=data.friends;unreadByPeer={};renderFriends();if(active&&!friends.some(function(f){return f.id===active;})){active=null;records={};dm.find('.friend-messages').empty();dm.prop('hidden',true);}alerts.children('[data-peer]').each(function(){var id=$(this).attr('data-peer');if(!friends.some(function(f){return f.id===id;}))$(this).remove();});data.inbox.forEach(function(item){var read=marker('read',item.sender);if(!newer(item.last_id,read)){api('read',{peer:item.sender,id:read});removeAlert(item.sender);return;}unreadByPeer[item.sender]=Number(item.unread)||1;if(active===item.sender&&!dm.prop('hidden')&&!document.hidden)load(false);else alertFriend(item.sender,item.last_id);});renderUnread();if(active&&!dm.prop('hidden'))load(false);});}
 levelRanking.find('header button').on('click',function(){levelRanking.prop('hidden',true);});
 levelRankingButton.on('click',function(){levelRanking.prop('hidden',false);levelRanking.find('.level-ranking-status').text('현재 레벨이 높은 순서로 불러오는 중입니다.').show();levelRanking.find('.level-ranking-list').empty();$.getJSON('/api/level-ranking').done(function(data){var list=levelRanking.find('.level-ranking-list').empty();(data.list||[]).forEach(function(row){var nickname=String(row.nickname||'이름 없음');$('<div class="level-ranking-row">').append($('<strong class="level-ranking-position">').text(row.rank),$('<span class="level-ranking-name">').text(nickname),$('<b class="level-ranking-level">').text('Lv.'+row.level),$('<small class="level-ranking-score">').text(Number(row.score).toLocaleString()+' 경험치')).appendTo(list);});levelRanking.find('.level-ranking-status').text(list.children().length?'총 '+list.children().length+'명':'랭킹 기록이 없습니다.');}).fail(function(e){levelRanking.find('.level-ranking-status').text(error(e));});});
 setInterval(function(){var lobby=typeof getOnly==='function'&&getOnly()==='for-lobby';levelRankingButton.css('display',lobby?'inline-flex':'none');if(!lobby)levelRanking.prop('hidden',true);var guest=isGuest();launcher.toggle(!guest);loginLauncher.toggle(guest);},500);
 $(document).on('visibilitychange',function(){if(!document.hidden){load(false);poll();}});
 setInterval(poll,2500);poll();
 window.showMentionNotice=function(profile,text,scope,authorId){
  if(authorId===$data.id||profile.id===$data.id)return;var me=$data.users&&$data.users[$data.id];if(!me)return;
  if(scope==='room'&&(!$data.room||!($data.room.players||[]).some(function(p){return (typeof p==='string'?p:p.id)===$data.id;})))return;
  var n=me.profile&&(me.profile.title||me.profile.name);if(!n)return;var needle='@'+n,index=String(text).indexOf(needle),found=false;while(index>=0){var before=index?text.charAt(index-1):'',after=text.charAt(index+needle.length);if((!before||/\s/.test(before))&&(!after||/[\s.,!?~:;，。！？]/.test(after))){found=true;break;}index=text.indexOf(needle,index+1);}if(!found)return;
  var card=$('<section class="friend-toast mention-toast">').appendTo(alerts);$('<strong>').text((profile.title||profile.name||'플레이어')+'님이 멘션을 했어요').appendTo(card);$('<span class="mention-scope">').text(scope==='room'?'방채팅':'메인채팅').appendTo(card);$('<button class="friend-dismiss">').text('닫기').appendTo(card).on('click',function(){card.remove();});setTimeout(function(){card.remove();},10000);
 };
 var suggestions=$('<div id="MentionSuggestions" role="listbox" aria-label="멘션할 플레이어" hidden>').appendTo('body');
 $('#Talk')[0].addEventListener('keydown',function(e){if(suggestions.prop('hidden')||e.isComposing)return;var buttons=suggestions.children('button'),selected=buttons.index(buttons.filter('.selected'));if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();e.stopImmediatePropagation();selected=selected<0?(e.key==='ArrowDown'?0:buttons.length-1):(selected+(e.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length;buttons.removeClass('selected').eq(selected).addClass('selected')[0].scrollIntoView({block:'nearest'});}else if(e.key==='Enter'&&buttons.length){e.preventDefault();e.stopImmediatePropagation();buttons.eq(selected<0?0:selected).trigger('pointerdown');}else if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();suggestions.prop('hidden',true);}},true);
 $('#Talk').on('input.mention',function(){var input=this,pos=input.selectionStart||0,before=input.value.slice(0,pos),match=before.match(/(?:^|\s)@([^@\n]*)$/);suggestions.empty().prop('hidden',true);if(!match)return;var scope=$data.chatScope||'main',query=match[1].toLowerCase(),players=($data.room&&$data.room.players||[]).map(function(p){return typeof p==='string'?p:p.id;});Object.keys($data.users||{}).filter(function(id){return id!==$data.id&&!$data.users[id].robot&&(scope==='main'||players.indexOf(id)>=0);}).map(function(id){var u=$data.users[id];return{id:id,name:u.profile&&(u.profile.title||u.profile.name)};}).filter(function(u){return u.name&&u.name.toLowerCase().indexOf(query)>=0;}).slice(0,8).forEach(function(u){$('<button type="button" role="option">').text('@'+u.name).appendTo(suggestions).on('pointerdown',function(e){e.preventDefault();var start=pos-match[1].length-1;input.value=input.value.slice(0,start)+'@'+u.name+' '+input.value.slice(pos);input.focus();input.setSelectionRange(start+u.name.length+2,start+u.name.length+2);suggestions.prop('hidden',true);});});if(suggestions.children().length){var r=input.getBoundingClientRect();suggestions.css({left:r.left,bottom:innerHeight-r.top+4,width:Math.min(r.width,320)}).prop('hidden',false);}}).on('blur',function(){setTimeout(function(){suggestions.prop('hidden',true);},150);});
});
